### ISSUE TITLE
Widget not get updated

### ISSUE THREAD

**Issue by setoelkahfi** [JeffreyCA/spotify-recently-played-readme#10]
Thanks for this!
Why does my widget not get updated whenever I finished listening to a new track? Is it the current implementation? I guess it's more a question than an issue.

**Comment by JeffreyCA** [comment]
It's not a "live" widget, so you have to refresh the page to see updates, if that's what you mean.

Another thing is that I set the following `Cache-Control` headers:

```
res.setHeader('Cache-Control', 's-maxage=60, stale-while-revalidate');
```

**Comment by setoelkahfi** [comment]
Yeah, I think it was the cache. I reload the page after playing a new track.
