### ISSUE TITLE
Clickable functionality under Github's Camo engine

### ISSUE THREAD

**Issue by GrungeElFz** [JeffreyCA/spotify-recently-played-readme#34]
In **Vercel App**, each `<li>` element for the track is clickable.
Each track will route to its Spotify's link

For **Github README** profile page, the whole element will be rendered by [Github's Camo](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls) ;
hence, the element will simply be rendered as an image.

---

Vercel App:
https://spotify-recently-played-readme.vercel.app/

My README:
https://github.com/GrungeElFz/GrungeElFz

---

Are there any solutions to achieve a clickable functionality for each individual track?

**Comment by JeffreyCA** [comment]
Hi, yes you're right - it's unfortunately a limitation of how GitHub renders SVGs. One solution could be to render each track as an individual SVG, and have some automation in place to periodically update your GitHub README.md, linking each SVG to the Spotify link.

Example (only the spotify links would change periodically):
```
[![](<myapp>/api?user=<user>&position=1)](<spotify link 1>)
[![](<myapp>/api?user=<user>&position=2)](<spotify link 2>)
[![](<myapp>/api?user=<user>&position=3)](<spotify link 3>)
```

This would be out of scope of this project however

**Comment by GrungeElFz** [comment]
Appreciate it  🙏
