### ISSUE TITLE
Difficulty in Connecting to Firebase

### ISSUE THREAD

**Issue by jonodjlee** [JeffreyCA/spotify-recently-played-readme#5]
Hi @JeffreyCA, 

This is a fantastic piece of work! I was trying to create my own instance on Vercel using the template you set up, but I am having difficulty with the Firebase integration. Could you please explain how to do it, as I haven't used Firebase before? Thanks :))

**Comment by JeffreyCA** [comment]
Hi @jonodjlee, sure thing! I've outlined some steps below, let me know if you need more clarification or encounter any issues.

1. Create a Firebase project: https://console.firebase.google.com/
2. Setup a Realtime Database and make note of the database URL (it's something like `https://project-name.firebaseio.com/`)
3. Set the database rules to something like:
    <img width="1237" alt="Screen Shot 2021-01-06 at 3 21 35 PM" src="https://user-images.githubusercontent.com/9157833/103816415-eece0c80-5032-11eb-8976-ae52c1b0a315.png">
4. Navigate to the **Service Accounts** tab in the Firebase project settings and click **Generate private key**. This will download a JSON file. In the JSON file you'll find the project ID, private key, and client email.
5. Base64 encode the private key (it's ok to keep all the newlines):
    ```sh
    $ echo "-----BEGIN PRIVATE KEY-----(...)-----END PRIVATE KEY-----\n" | base64
    ``` 

    In Vercel, set that as the value of the secret environment variable `FIREBASE_PRIVATE_KEY_B64`.

6. Set the secret environment variable `FIREBASE_PROJECT_ID` to your project ID.
7. Set the secret environment variable `FIREBASE_DATABASE_URL` to the Firebase database URL (from step 2) 
8. Set the secret environment variable `FIREBASE_CLIENT_EMAIL` to the client email.

9. Redeploy your Vercel app.

Now if you try to link a Spotify account, you should see a new entry appear in the Realtime Database.

Hope that helps!

**Comment by jonodjlee** [comment]
Thanks for those steps @JeffreyCA! Worked perfectly 🚀 

Thanks again for this incredible project you've put together 😁

**Comment by JeffreyCA** [comment]
Thank you for the feedback and kind words, I'm happy to see others use it! 😊

I added the instructions above to the wiki as well ([link](https://github.com/JeffreyCA/spotify-recently-played-readme/wiki/Setup-Firebase-for-your-own-Vercel-instance)). Closing this issue now
