### ISSUE TITLE
environment variables

### ISSUE THREAD

**Issue by Nithin552** [JeffreyCA/spotify-recently-played-readme#8]
hey does it require firebase environment variables or only SPOTIFY_REFRESH_TOKEN, SPOTIFY_CLIENT_ID, SPOTIFY_SECRET_ID necessary to deploy in vercel for spotify-recently-played-readme? can you clarify this..

**Comment by JeffreyCA** [comment]
See the required environment variables [here](https://github.com/JeffreyCA/spotify-recently-played-readme#deploying-own-vercel-instance)

**Comment by Nithin552** [comment]
yeah thanks will message you later after deploying

**Comment by Nithin552** [comment]
hey is it necessary to deploy WARMUP_KEY environmental variable too or only firebase_database_url is enough?

**Comment by JeffreyCA** [comment]
`WARMUP_KEY` is optional

**Comment by Nithin552** [comment]
hey where can i trace this FIREBASE_PRIVATE_KEY_B64 env variable in firebase can you help me out??

**Comment by Nithin552** [comment]
can you give example how to encode the firebase pvt key B64

**Comment by JeffreyCA** [comment]
> can you give example how to encode the firebase pvt key B64

See this: https://superuser.com/questions/120796/how-to-encode-base64-via-command-line
